//
//  main.swift
//  problem2
//
//  Created by Rafael M Mudafort on 7/3/17.
//  Copyright © 2017 RiffRaff. All rights reserved.
//

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import Foundation

var count = 0
var sum = 0
var pm1 = 1
var p = 1
var tmp = 0

while (p <= 4000000) {
    count += 1
    tmp = p
    p += pm1
    pm1 = tmp
    if euler.dividesEvenly(2, into: pm1) {
        print("\(count) - \(pm1) even")
        sum += pm1
    } else {
        print("\(count) - \(pm1) odd")
    }
}

print("sum of even values in fibonacci \(sum)")
